"""added foreignkey constraint

Revision ID: cf5dc88b2cd4
Revises: a0d542199c75
Create Date: 2023-06-26 10:39:46.357805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5dc88b2cd4'
down_revision = 'a0d542199c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_author_id', table_name='books')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_index('ix_books_author_id', 'books', ['author_id'], unique=False)
    # ### end Alembic commands ###
